name: CI for Trunk-Based Development

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m venv ci-venv
          source ci-venv/bin/activate
          pip install -r requirements.txt

      - name: Run tests
        run: |
          source ci-venv/bin/activate
          pytest
        
      - name: Run tests with coverage
        run: |
          source ci-venv/bin/activate
          pytest --cov=app

      - name: Run Black
        run: |
          source ci-venv/bin/activate
          black --check --exclude 'ci-venv' .

      - name: Run Flake8
        run: |
          source ci-venv/bin/activate
          flake8 --exclude=ci-venv/* .

      - name: Merge to main
        if: success()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout main
          git merge /for/main
          git push origin main
